DO $script$
BEGIN

CREATE TABLE IF NOT EXISTS dbo.manga (
	manga_id INT GENERATED BY ALWAYS AS IDENTITY NOT NULL,
	url_id INT NOT NULL,
	manga_name VARCHAR(150) NOT NULL,
	manga_desc VARCHAR,
	current_chapter INT,
	last_chapter INT NOT NULL,
	manga_chapter_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
)
WITH (oids = false);

-- Create primary key
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'dbo'
	AND table_name = 'manga'
	AND constraint_type = 'PRIMARY KEY'
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS dbo.manga
		ADD CONSTRAINT pk_manga_id
		PRIMARY KEY (manga_id);
END IF;

-- Create foreign key fk_manga_url_id
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.columns
	WHERE table_schema = 'dbo'
	AND table_name = 'url'
	AND column_name = 'url_id'
	LIMIT 1
)
THEN
	raise notice '!!!WARNING!!! Table dbo.url or column url_id not found!';
ELSIF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'dbo'
	AND table_name = 'manga'
	AND lower(constraint_name) = lower('fk_manga_url_id')
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS dbo.manga
		ADD CONSTRAINT fk_manga_url_id
		FOREIGN KEY (url_id) 
		REFERENCES dbo.url (url_id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
		NOT DEFERRABLE;
END IF;

COMMENT ON TABLE dbo.manga IS 'Манга';

COMMENT ON COLUMN dbo.manga.manga_id IS 'Идентификатор манги';
COMMENT ON COLUMN dbo.manga.url_id IS 'Идентификатор сайта (последняя вышедшая глава)';
COMMENT ON COLUMN dbo.manga.manga_name IS 'Название манги';
COMMENT ON COLUMN dbo.manga.manga_desc IS 'Описание состояния';
COMMENT ON COLUMN dbo.manga.current_chapter IS 'Последняя прочитаная глава';
COMMENT ON COLUMN dbo.manga.last_chapter IS 'Последняя вышедшая глава';
COMMENT ON COLUMN dbo.manga.manga_chapter_data IS 'Дата выхода главы';

END;
$script$;
